/**
 * FOOTER JOKES — REPLACE ME.
 * Tiny mono-caps footer lines. The first one is the canonical spec line.
 */
export const FOOTER_LINES: string[] = [
  "THIS INTERFACE IS PART OF THE AURA OPERATING SYSTEM. UNAUTHORIZED DRIP IS STRICTLY MONITORED.",
  "AURA OS IS NOT RESPONSIBLE FOR ANY OUTFITS PURCHASED AS A RESULT OF THIS SCAN.",
  "DRIP SENSORS CALIBRATED AGAINST 4,000 THRIFTED WORK JACKETS.",
  "NO MANNEQUINS WERE HARMED IN THE MAKING OF THIS OPERATING SYSTEM.",
];
