import { NEAR_ZERO_MAX } from "@/lib/scoring";

/**
 * Tiger Data (TimescaleDB) schema. Idempotent: run on first connection
 * (TigerStore) or with `npm run db:setup`.
 *
 * Time-series on purpose:
 * - scans and judge_scores are hypertables partitioned by created_at.
 * - aura_15m is a real-time continuous aggregate (15-minute buckets: scans,
 *   average / best / worst aura, wide swings, judge disagreements) behind
 *   the leaderboard's "aura over the event" chart and hottest-hour stat.
 * - judge_scores feeds the adaptive scoring cutoff (today's ratings per judge).
 *
 * No foreign keys into hypertables; ids are uuids generated by the app.
 */
export const TIGER_SCHEMA: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS scans (
    id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    image_hash text NOT NULL,
    aura integer NOT NULL,
    judge_count smallint NOT NULL DEFAULT 1,
    disagree boolean NOT NULL DEFAULT false,
    analysis jsonb NOT NULL,
    breakdown jsonb NOT NULL,
    PRIMARY KEY (id, created_at)
  )`,
  `SELECT create_hypertable('scans', by_range('created_at', INTERVAL '1 day'), if_not_exists => TRUE)`,
  `CREATE INDEX IF NOT EXISTS scans_image_hash_idx ON scans (image_hash, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS scans_id_idx ON scans (id)`,

  `CREATE TABLE IF NOT EXISTS judge_scores (
    created_at timestamptz NOT NULL,
    scan_id uuid NOT NULL,
    judge text NOT NULL,
    model text NOT NULL,
    specialness real NOT NULL,
    sentiment text NOT NULL,
    cutoff real NOT NULL,
    aura integer NOT NULL
  )`,
  `SELECT create_hypertable('judge_scores', by_range('created_at', INTERVAL '1 day'), if_not_exists => TRUE)`,
  `CREATE INDEX IF NOT EXISTS judge_scores_judge_idx ON judge_scores (judge, created_at DESC)`,

  `CREATE TABLE IF NOT EXISTS players (
    handle text PRIMARY KEY,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,

  `CREATE TABLE IF NOT EXISTS leaderboard_entries (
    id uuid PRIMARY KEY,
    scan_id uuid NOT NULL,
    handle text,
    nickname text NOT NULL CHECK (char_length(nickname) <= 30),
    aura integer NOT NULL,
    standout text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS leaderboard_entries_scan_idx ON leaderboard_entries (scan_id)`,
  `CREATE INDEX IF NOT EXISTS leaderboard_entries_aura_idx ON leaderboard_entries (aura DESC)`,
  `CREATE INDEX IF NOT EXISTS leaderboard_entries_created_idx ON leaderboard_entries (created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS leaderboard_entries_handle_idx ON leaderboard_entries (handle, created_at)`,

  `CREATE TABLE IF NOT EXISTS battles (
    id uuid PRIMARY KEY,
    scan_a uuid NOT NULL,
    scan_b uuid NOT NULL,
    roast text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,

  // Aura Battles: N players per battle (duel or squad). scan_a / scan_b keep the first two for old readers.
  `ALTER TABLE battles ADD COLUMN IF NOT EXISTS mode text NOT NULL DEFAULT 'duel'`,
  `ALTER TABLE battles ADD COLUMN IF NOT EXISTS outcome jsonb`,
  `ALTER TABLE battles ADD COLUMN IF NOT EXISTS commentary text`,
  `CREATE INDEX IF NOT EXISTS battles_created_idx ON battles (created_at DESC)`,
  // One row per player per battle: rivalries and streaks are self-joins on handle ordered by time.
  `CREATE TABLE IF NOT EXISTS battle_players (
    battle_id uuid NOT NULL,
    slot smallint NOT NULL,
    scan_id uuid NOT NULL,
    handle text,
    total integer NOT NULL,
    place smallint NOT NULL,
    won boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (battle_id, slot)
  )`,
  `CREATE INDEX IF NOT EXISTS battle_players_handle_idx ON battle_players (handle, created_at)`,

  `CREATE TABLE IF NOT EXISTS cards (
    id uuid PRIMARY KEY,
    scan_id uuid,
    battle_id uuid,
    png bytea NOT NULL,
    nft_signature text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  // The public feed is the cards table: a card is posted the moment it is saved.
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'scan'`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS headline integer NOT NULL DEFAULT 0`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS target integer NOT NULL DEFAULT 0`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS title text NOT NULL DEFAULT ''`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS verdict text`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS caption text`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS parent_id uuid`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS slot smallint`,
  `CREATE INDEX IF NOT EXISTS cards_feed_idx ON cards (created_at DESC) WHERE parent_id IS NULL`,
  `CREATE INDEX IF NOT EXISTS cards_parent_idx ON cards (parent_id)`,

  // Phone companion (/scan): where each scan / card / entry came from, the phone that made it
  // (only it may start a challenge; never sent to clients), and admin removals.
  `ALTER TABLE scans ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'mirror'`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'mirror'`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS device_id text`,
  `ALTER TABLE cards ADD COLUMN IF NOT EXISTS hidden_at timestamptz`,
  `ALTER TABLE leaderboard_entries ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'mirror'`,
  `ALTER TABLE leaderboard_entries ADD COLUMN IF NOT EXISTS device_id text`,
  `ALTER TABLE leaderboard_entries ADD COLUMN IF NOT EXISTS hidden boolean NOT NULL DEFAULT false`,
  `CREATE INDEX IF NOT EXISTS leaderboard_entries_device_idx ON leaderboard_entries (device_id) WHERE device_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS cards_hidden_idx ON cards (hidden_at) WHERE hidden_at IS NOT NULL`,
  // Only written with STORE_RAW_PHOTOS=true (off by default): the EXIF-stripped upload.
  `CREATE TABLE IF NOT EXISTS raw_photos (
    scan_id uuid PRIMARY KEY,
    mime_type text NOT NULL,
    data bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,

  // Challenge links (/c/[id]) and each friend's accept (its battle + feed card).
  `CREATE TABLE IF NOT EXISTS duels (
    id text PRIMARY KEY,
    card_id uuid NOT NULL,
    scan_id uuid NOT NULL,
    device_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS duels_card_idx ON duels (card_id)`,
  `CREATE TABLE IF NOT EXISTS duel_accepts (
    id uuid PRIMARY KEY,
    duel_id text NOT NULL,
    card_id uuid NOT NULL,
    scan_id uuid NOT NULL,
    battle_id uuid NOT NULL,
    feed_card_id uuid,
    device_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS duel_accepts_card_idx ON duel_accepts (duel_id, card_id)`,
  `CREATE INDEX IF NOT EXISTS duel_accepts_duel_idx ON duel_accepts (duel_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS duel_accepts_feed_idx ON duel_accepts (feed_card_id) WHERE feed_card_id IS NOT NULL`,

  `CREATE TABLE IF NOT EXISTS reactions (
    card_id uuid NOT NULL,
    emoji text NOT NULL,
    client_id text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (card_id, emoji, client_id)
  )`,

  `CREATE TABLE IF NOT EXISTS fit_history (
    id bigserial PRIMARY KEY,
    signature text NOT NULL,
    seed text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,

  // Kiosk relay (lib/server/relay.ts): the mirror's status, remote commands, the
  // challenger line and mirror launch requests, shared by the kiosk laptop and the
  // public server so /admin works from either.
  `CREATE TABLE IF NOT EXISTS kiosk_status (
    id smallint PRIMARY KEY,
    status jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS remote_commands (
    id bigserial PRIMARY KEY,
    command text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS challengers (
    id bigserial PRIMARY KEY,
    name text NOT NULL,
    target double precision NOT NULL DEFAULT 0,
    card_id text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    called_at timestamptz,
    removed boolean NOT NULL DEFAULT false
  )`,
  `CREATE INDEX IF NOT EXISTS challengers_called_idx ON challengers (called_at DESC) WHERE called_at IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS mirror_launches (
    id bigserial PRIMARY KEY,
    requested_at timestamptz NOT NULL DEFAULT now(),
    taken_at timestamptz
  )`,

  `CREATE MATERIALIZED VIEW IF NOT EXISTS aura_15m
    WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
    SELECT
      time_bucket(INTERVAL '15 minutes', created_at) AS bucket,
      count(*) AS scans,
      avg(aura) AS avg_aura,
      max(aura) AS max_aura,
      min(aura) AS min_aura,
      count(*) FILTER (WHERE abs(aura) > ${NEAR_ZERO_MAX}) AS swings,
      count(*) FILTER (WHERE disagree) AS disagreements
    FROM scans
    GROUP BY bucket
    WITH NO DATA`,
  `SELECT add_continuous_aggregate_policy('aura_15m',
    start_offset => INTERVAL '3 days',
    end_offset => INTERVAL '1 minute',
    schedule_interval => INTERVAL '1 minute',
    if_not_exists => TRUE)`,
];
